/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.event.ActionListener;
import static java.lang.Thread.sleep;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class GUI_Game extends javax.swing.JFrame{
    public boolean isPlaying = false;
    public int sec = 0, min = 0 , hour = 0;
    /**
     * Creates new form GUI_Game
     */
    public GUI_Game(String title) {
        super("Game of " + title);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(850, 850);
        new runTimer();

    }

    public JPanel getpGame() {
        return pGame;
    }

    public JLabel getLblHour() {
        return lblHour;
    }

    public JLabel getLblMin() {
        return lblMin;
    }

    public JLabel getLblSec() {
        return lblSec;
    }

    public JButton getBtnGame() {
        return btnGame;
    }

    public class runTimer extends Thread {
        public runTimer() {
            start();
        }

        public void run() {
            while (isPlaying) {
                try {
                    sec++;
                    if (sec == 60) {
                        sec = 0;
                        min++;
                    }
                    if(min == 60){
                        min = 0;
                        hour++;
                    }
                    lblHour.setText(String.valueOf(hour));
                    lblMin.setText(String.valueOf(min));
                    lblSec.setText(String.valueOf(sec));
                    sleep(1000);
                } catch (InterruptedException ex) {
                }
            }
        }
    }
    
    public void addStartListener(ActionListener al) {
        btnGame.addActionListener(al);
        isPlaying = true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pTime = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblHour = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        lblSec = new javax.swing.JLabel();
        btnGame = new javax.swing.JButton();
        pGame = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Time:");

        lblHour.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHour.setForeground(new java.awt.Color(255, 0, 0));
        lblHour.setText("0");

        lblMin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMin.setForeground(new java.awt.Color(255, 0, 0));
        lblMin.setText("0");

        lblSec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSec.setForeground(new java.awt.Color(255, 0, 0));
        lblSec.setText("0");

        btnGame.setText("READY!");

        javax.swing.GroupLayout pTimeLayout = new javax.swing.GroupLayout(pTime);
        pTime.setLayout(pTimeLayout);
        pTimeLayout.setHorizontalGroup(
            pTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTimeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSec)
                .addGap(209, 209, 209)
                .addComponent(btnGame, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pTimeLayout.setVerticalGroup(
            pTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblHour)
                    .addComponent(lblMin)
                    .addComponent(lblSec)
                    .addComponent(btnGame))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pGame.setPreferredSize(new java.awt.Dimension(850, 850));

        javax.swing.GroupLayout pGameLayout = new javax.swing.GroupLayout(pGame);
        pGame.setLayout(pGameLayout);
        pGameLayout.setHorizontalGroup(
            pGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        pGameLayout.setVerticalGroup(
            pGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 917, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pGame, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pGame, javax.swing.GroupLayout.DEFAULT_SIZE, 917, Short.MAX_VALUE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblSec;
    private javax.swing.JPanel pGame;
    public javax.swing.JPanel pTime;
    // End of variables declaration//GEN-END:variables


}
